### ISSUE TITLE
Pinning the plugin version doesn't pin the linter version

### ISSUE THREAD

**Issue by tessereth** [buildkite-plugins/plugin-linter-buildkite-plugin#2]
While you can pin the version of the plugin in `pipeline.yml`, the plugin just pulls the latest version of the `plugin-linter` docker image. This can cause builds to fail under your feet if something changes in https://github.com/buildkite-plugins/buildkite-plugin-linter.

**Comment by tessereth** [comment]
The linter now requires a plugin example in the README. That possibly came in when you changed to TAP output, I didn't look that far. But it used to just log and continue if it didn't find one. I can see an argument for requiring it, but I'm just the special snowflake that it doesn't work for.

**Comment by toolmantim** [comment]
Thanks for being patient zero for these problems! It looks like you have an example in the README though?

```yml
  - label: annotate
    plugins:
      bugcrowd/test-summary#v1.1.0:
        inputs:
          - label: rspec
            artifact_path: artifacts/rspec*
            type: junit
          - label: ava
            artifact_path: artifacts/ava.tap
            type: tap
          - label: rubocop
            artifact_path: artifacts/rubocop.txt
            type: oneline
        formatter:
          type: details
        context: test-summary
```

Would you mind opening an issue on https://github.com/buildkite/buildkite-plugin-linter and I'll get that fixed for you?
