### ISSUE TITLE
Local plugins

### ISSUE THREAD

**Issue by changusmc** [buildkite-plugins/plugin-linter-buildkite-plugin#37]
Hello, 

I'm going through the example in https://buildkite.com/docs/plugins/writing and trying to create the plugin in my existing local codebase.

Below is the directory structure

```
file-counter-buildkite-plugin ➤ tree                                                                                                                                                                                      
.
├── README.md
├── hooks
│   └── post-command
├── package.json
├── plugin.yml
└── tests
    └── post-command.bats
```

In order to use this plugin, I have to add this to my pipeline
```yml
steps:
  - command: ls
    plugins:
      - ./ci/buildkite/plugins/file-counter-buildkite-plugin#v1.0.0:
          pattern: '*.md'
```
Therefore, I want to add that to my README as well.

However, `plugin-linter-buildkite-plugin` doesn't like my command when I try to validate my plugin

```
file-counter-buildkite-plugin ➤ docker run -it --rm -v "$(PWD):/plugin:ro" buildkite/plugin-linter --id ./ci/buildkite/plugins/file-counter-buildkite-plugin                                                              git:scratch/changd/buildkite*
lint

Lint a buildkite plugin

Options:
  --id, --name  Id of the plugin (e.g. my-org/my-plugin)     [string] [required]
  --path        Path to the plugin                           [string] [required]
  --readme      Readme filename                  [string] [default: "README.md"]
  --help        Show help                                              [boolean]

--id can not end with -buildkite-plugin. Did you mean ./ci/buildkite/plugins/file-counter?
```

I also tried versioning it.
```yml
steps:
  - command: ls
    plugins:
      - ./ci/buildkite/plugins/file-counter-buildkite-plugin#v1.0.0:
          pattern: '*.md'
```

```
file-counter-buildkite-plugin ➤ docker run -it --rm -v "$(PWD):/plugin:ro" buildkite/plugin-linter --id ./ci/buildkite/plugins/file-counter-buildkite-plugin\#v1.0.0                                                      
TAP version 13
ok 1 - plugin.yml is valid
not ok 2 - No readme config examples found with plugin id './ci/buildkite/plugins/file-counter-buildkite-plugin#v1.0.0'. Have you configured the linter with the correct plugin id?
ok 3 - Readme version numbers are up-to-date (undefined)
1..3
# failed 1 of 3 tests
# time=50.012ms
```
