### ISSUE TITLE
Support interpolation of variables

### ISSUE THREAD

**Issue by peter-svensson** [buildkite-plugins/plugin-linter-buildkite-plugin#57]
When using environment variables and interpolation in a buildkite pipeline, like:

```yaml
steps:
  - label: test
    plugins:
      - https://github.com/any-buildkite-plugin#v1:
          target: $${TARGET}
    env:
      TARGET: 'dev'
```

It would be nice to be able to document this example in the `README.md` of the plugin.

A plugin with the following configuration snippet:
```yaml
configuration:
  properties:
    target:
      type: string
      enum: [ "dev", "prod"]
```
will fail linting with: `message: must be equal to one of the allowed values`

Since the linter plugin is running as a command it is hard to do any changes to the `README.md` file in the repository before the linter runs. One simple solution would be to run the linter as a `post-command` hook instead, that way it is possible to do som `sed` replacement or something similar before the actual linting  🤷‍♂️ ?

**Comment by toote** [comment]
@peter-svensson sorry for the delay getting back to you!

Unfortunately, the linter uses standard libraries to validate JsonSchemas against the extracted pipelines in examples and does not do any kind of uploading or evaluation of the pipeline itself to interpret what would happen at execution time.

With that said, I believe that the linter is technically correct in pointing out the example is invalid. Your plugin spec states that the `target` element of your configuration should be one of `dev` or `prod` but the value at execution is actually the string `$TARGET` that your plugin then evaluates according to its execution context and resolves to `dev`... but the value of the option is neither `dev` nor `prod` so the error is therefore correct. Based on the fact that your plugin's code does variable interpolation you might want to change the spec to something like:

```
configuration:
  properties:
    target:
      type: string
      oneOf:
         - enum: [ "dev", "prod"]
         - pattern: "^\$\${?[A-Za-z_][A-Za-z0-9_-]*}?$"
```

This means that your option can be the literals `dev` or `prod` or any string that has a double-escaped variable, making your example valid (note that I have not tested the regex so you may have to tweak it).
